version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # Listening interface for Kafka within the container
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Advertised address for other services to connect
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  spark:
    build: ./
    volumes:
      - ./main:/main
    depends_on:
      - kafka
    environment:
      SPARK_MASTER: local